# Generated by Django 3.1.2 on 2020-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_remove_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='occupants',
            new_name='health',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
